apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kodekloud-project
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: applications
  project: default
  revisionHistoryLimit:
  source:
    repoURL: https://github.com/lakinnawonu/Openshift-kubernetes.git
    targetRevision: HEAD
    path: kodekloud-project
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreatNamespace=true
