apiVersion: v1
kind: LimitRange
metadata:
  name: ex280-limits
  namespace: bluebook
spec:
  limits:
    - type: Pod
      max:
        memory: 300Mi
        cpu: 500m
      min:
        memory: 100Mi
        cpu: 10m
    - type: Container
      min:
        cpu: 10m
      max:
        cpu: 500m
      defaultRequest:
        cpu: 100m


