apiVersion: v1
data:
  htpasswd: am9iczokMnkkMDUkSlhnSmhVSjljdUR4ZU9qd0J0MFcwZVp6VTZHRE9nZFZva1dCTnBQRU9ZalpObjlsbjdrcXkKd296bmlhazokMnkkMDUkbVZscmdaTjhaLldQb3Rud0kxQzQzdThuejFMdmVuVTNEUjZZWk03M3hRdHNHazEzR1NMUHUKY29sbGluczokMnkkMDUkV2dQRnlYNkVYREFPVGNTV1IydlJtT2JwSS55U2hnZGFsR1Y4cWJLdzRmc2NnMEYwLlNPdEMKYWRsZXJpbjokMnkkMDUkT2RIUUFJbmUzbHY2QlFscjh1VGlCZVBaLkdSSXlsOTZ4RHVuUTNpY0VHdmFBRFE1WUhvMHkKYXJtc3Ryb25nOiQyeSQwNSRINTZIZEdCM3kuWmdSSEZCV1pJVE51Z1A5VHZ4M1ZrTXhDV2IuREdpcXU2TU1pMTFyejM5aQo=
kind: Secret
metadata:
  name: htpass-idp-ex280
  namespace: openshift-config
